config/routes.rb
Rails.application.routes.draw do

  controller :register do
    get 'register' => :index
    post 'register' => :update
  end

  resources :dog_owners

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :dogs

  root 'sessions#new'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
	validates :name, :breed, :dob, presence: true

	before_destroy :ensure_not_referenced_by_any_dog_owner

	def get_expiry_date
		@record = DogOwner.find_by(dog_id: id)
		if @record.registeredtill
			return @record.registeredtill.to_formatted_s(:long)
		else
			return "Expired"
		end
	end

	private

	# Check that we are not going to break a reference
	def ensure_not_referenced_by_any_dog_owner

		# Check for a link to an owner
		@record = DogOwner.find_by(dog_id: id)
		if @record
			errors.add(:base, 'Dog owner present')
			return false
		else
			return true
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    owner = User.find_by(id: session[:user_id])
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { 
          #redirect_to @dog
          redirect_to new_dog_owner_path(owner_id: owner.id, dog_id: @dog.id), 
          notice: 'Dog was successfully created.' 
        }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy

    # Remove link to owner
    @record = DogOwner.find_by(dog_id: @dog.id)
    if @record
      @record.destroy
    end

    # Remove dog
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed, :dob)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', User.home_url(User.find_by(id: session[:user_id])) %>

app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.dob %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dog.dob %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', User.home_url(User.find_by(id: session[:user_id])) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dog Registration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class='<%= controller.controller_name %>'>
	<div id="banner">
		<%= @page_title || "Dog Registrations" %>
	</div>
	<div id="columns">
		<div id="side">
			<ul>
				<li><a href="http://localhost:3000/">Home</a></li>

				<li><%= link_to 'Register', new_user_path %></li>
			</ul>

			<% if session[:user_id] %>
				<div id="user">
					<%= "User: #{User.find_by(id: session[:user_id]).username}" %>
					<%= button_to 'Logout', logout_path, method: :delete %>
				</div>
			<% end %>
		</div>
	</div>	

	<div id="main">
		<%= yield %>
	</div>

</body>
</html>